[template]
ignore = [
    "solutions/rust/lib",
    "README.md",
    "LICENSE",
]

[placeholders.year]
type = "string"
prompt = "year"
regex = "^([0-9]){4}$"

[placeholders.day]
type = "string"
prompt = "day"
regex = "^(0[1-9])|(1[0-9])|(2[0-5])$"
